#!/usr/bin/env php
<?php

use Ahc\Cli\Application;
use App\Console\Migration\DbToEmailManualMigrationCommand;
use App\Console\Migration\DbToEmailMigrationCommand;
use App\Console\Migration\DbToLegendMigrationCommand;
use App\Console\Migration\EmailToIdncMigrationCommand;
use App\Console\Migration\ImportReviewsMigrationCommand;
use App\Console\StatsCommand;
use App\Console\Users\UsersAddCommand;
use App\Console\Users\UsersDeleteCommand;
use App\Console\Users\UsersListCommand;
use App\Constants\App;

require __DIR__ . '/vendor/autoload.php';

if (PHP_SAPI !== 'cli' || isset($_SERVER['HTTP_USER_AGENT'])) {
  echo "Cli only!";
  exit;
}

require __DIR__ . '/bootstrap.php';
require __DIR__ . '/functions.php';

$app = new Application(
    'WikiUMA',
    App::version(),
);

$app->add(new StatsCommand());

// Migration
$app->add(new DbToEmailMigrationCommand());
$app->add(new DbToEmailManualMigrationCommand());
$app->add(new EmailToIdncMigrationCommand());
$app->add(new ImportReviewsMigrationCommand());
$app->add(new DbToLegendMigrationCommand());

// Users
$app->add(new UsersListCommand());
$app->add(new UsersAddCommand());
$app->add(new UsersDeleteCommand());

$app->handle($_SERVER['argv']);
